require: rubocop-rspec

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: true
