default: &default
  adapter: postgresql
  encoding: utf8
  database: PROJECT_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: crafter_development

test:
  <<: *default
  database: craftr_test
